name: medimage

channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib==3.7.0
  - nibabel==3.2.2
  - pandas==1.5.3
  - pillow==9.2.0
  - pydicom=1.2.2
  - pywavelets==1.1.1
  - scikit-image==0.18.2
  - scipy==1.7.0
  - setuptools==62.2.0
  - tqdm==4.65.0
  - pip
  - pip:
    - numpy==1.22.4
    - isort==5.10.1
    - ipykernel==6.15.1
    - ipywidgets==8.0.1
    - jupyter==1.0.0
    - networkx==2.8.5
    - neuroCombat==0.2.12
    - numpyencoder==0.3.0
    - protobuf==3.20.*
    - ray==2.5.1
    - scikit_image==0.18.2
    - SimpleITK==2.1.1.2
    - scikit_learn==1.2.2
    - seaborn==0.13.2
    - Sphinx==7.2.6
    - sphinx-carousel==1.2.0
    - sphinx-jsonschema==1.19.1
    - sphinx-rtd-dark-mode==1.2.4
    - sphinx-rtd-theme==0.5.2
    - wget==3.2
    - tabulate==0.9.0
    - xgboost==1.7.6
