[tool.poetry]
name = "medimage-pkg"
version = "0.9.0"
description = "MEDimage is a Python package for processing and extracting features from medical images"
authors = ["MEDomics Consortium <medomics.info@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/medomics/MEDomicsLab-develop"
repository = "https://github.com/medomics/MEDomicsLab-develop"
keywords = ["python", "ibsi", "medical-imaging", 
            "cancer-imaging-research", "radiomics", 
            "medical-image-analysis", "features-extraction", 
            "radiomics-extraction", "radiomics-features", "radiomics-analysis"]
packages = [ {include = "MEDimage"} ]

[tool.poetry.dependencies]
python = ">=3.8.0,<=3.10"
isort = "5.10.1"
ipykernel = "^6.15.1"
ipywidgets = "^8.0.1"
jupyter = "^1.0.0"
matplotlib = "3.7.0"
networkx = "2.8.5"
neuroCombat = "0.2.12"
nibabel = "3.2.2"
nilearn = "0.10.1"
numpy = "1.22.4"
numpyencoder = "0.3.0"
pandas = "1.5.3"
Pillow = "9.2.0"
protobuf = "3.20.*"
pycaret = "3.0.4"
pydicom = "1.2.2"
PyWavelets = "1.1.1"
ray = "2.5.1"
scikit-image = "0.18.2"
scipy = "1.7.0"
setuptools = "62.2.0"
SimpleITK = "2.1.1.2"
scikit_learn = "1.2.2"
seaborn = "0.13.2"
Sphinx = "7.2.6"
sphinx-carousel = "1.2.0"
sphinx-jsonschema = "1.19.1"
sphinx-rtd-dark-mode = "1.2.4"
tqdm = "4.65.0"
wget = "3.2"
tabulate = "0.9.0"
xgboost = "1.7.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
